In [1]:
import numpy as np
np.__version__

'1.21.6'

## Arreglos Lineales (Vectores)

In [3]:
# Lista
[12,11,5,15,14,20,16]

[12, 11, 5, 15, 14, 20, 16]

In [4]:
# Array
notas=np.array([12,11,5,15,14,20,16]) # Vector Fila
notas

array([12, 11,  5, 15, 14, 20, 16])

In [5]:
notas.shape

(7,)

In [8]:
notas2=notas.reshape(-1,1) # Vector Columna
notas2

array([[12],
       [11],
       [ 5],
       [15],
       [14],
       [20],
       [16]])

In [9]:
notas2.shape

(7, 1)

In [11]:
# Acceso & Slicing
notas[2],notas[2:],notas[:2],notas[:-1]  # Similar a las listas

(5,
 array([ 5, 15, 14, 20, 16]),
 array([12, 11]),
 array([12, 11,  5, 15, 14, 20]))